# Generated by Django 4.0.7 on 2022-12-06 22:41

from django.db import migrations, models
import media.media_paths


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video_preview",
            field=models.FileField(
                blank=True, null=True, upload_to=media.media_paths.video_previews_path
            ),
        ),
    ]
