# Generated by Django 4.0.7 on 2022-10-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['media_type', 'media_id'], name='posts_post_media_t_7b364b_idx'),
        ),
    ]
