# Generated by Django 4.0.7 on 2022-12-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_video_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
