# Generated by Django 4.0.7 on 2022-10-29 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_comments_number_post_likes_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
