# Generated by Django 4.0.7 on 2022-10-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='purchase_cost_amount',
            field=models.DecimalField(blank=True, decimal_places=50, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='post',
            name='purchase_cost_currency',
            field=models.CharField(blank=True, choices=[('usd', 'United States Dollar'), ('btc', 'Bitcoin')], default='usd', max_length=3),
        ),
    ]
