# Generated by Django 4.0.7 on 2022-11-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_uniqueview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feed_score',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='unique_views_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='views_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
