# Generated by Django 4.0.7 on 2022-12-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tip",
            name="created",
            field=models.DateTimeField(),
        ),
    ]
