# Generated by Django 4.0.7 on 2022-11-25 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatmessage_is_tip_message'),
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='tip_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.chatmessage'),
        ),
    ]
