# Generated by Django 4.0.7 on 2022-12-06 09:46

from django.conf import settings
from django.db import migrations, models
import media.media_paths
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cancelled_subscriptions',
            field=models.ManyToManyField(related_name='cancelled_subscribers', through='subscriptions.CancelledSubscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='cover_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=media.media_paths.cover_photos_path),
        ),
        migrations.AddField(
            model_name='account',
            name='post_comments',
            field=models.ManyToManyField(related_name='commented_on_by', through='posts.Comment', to='posts.post'),
        ),
        migrations.AddField(
            model_name='account',
            name='post_likes',
            field=models.ManyToManyField(related_name='liked_by', through='posts.Like', to='posts.post'),
        ),
        migrations.AddField(
            model_name='account',
            name='post_views',
            field=models.ManyToManyField(related_name='viewed_by', through='posts.View', to='posts.post'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=media.media_paths.profile_photos_path),
        ),
        migrations.AddField(
            model_name='account',
            name='purchased_videos',
            field=models.ManyToManyField(related_name='buyers', through='video_purchases.Purchase', to='posts.post'),
        ),
        migrations.AddField(
            model_name='account',
            name='saved_videos',
            field=models.ManyToManyField(related_name='saves', through='video_saves.VideoSave', to='posts.post'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribers', through='subscriptions.Subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='unique_post_views',
            field=models.ManyToManyField(related_name='unique_viewers', through='posts.UniqueView', to='posts.post'),
        ),
    ]
