# Generated by Django 4.0.7 on 2022-09-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_managers_remove_account_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_subscriptions_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='blocked_accounts_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='btc_wallet_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='account',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
        migrations.AddField(
            model_name='account',
            name='display_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='expired_subscriptions_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='notification_settings',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_info',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='account',
            name='purchased_videos_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='saved_videos_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='usd_wallet_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
