# Generated by Django 4.0.7 on 2022-12-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_account_cancelled_subscriptions_account_cover_photo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatorinfo",
            name="identity",
            field=models.JSONField(blank=True, default={"age": "", "legal_name": ""}),
        ),
    ]
