# Generated by Django 4.0.7 on 2022-09-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_active_subscriptions_number_account_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
