# Generated by Django 4.0.7 on 2022-09-22 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribers_number', models.PositiveIntegerField(default=0)),
                ('subscription_fee', models.JSONField(null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('identity', models.JSONField(null=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
