# Generated by Django 4.0.7 on 2022-10-09 02:14

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m/%d'),
        ),
    ]
