# Generated by Django 4.0.7 on 2022-09-23 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_creatorinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
