# Generated by Django 4.0.7 on 2022-09-25 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_creatorinfo_id_alter_creatorinfo_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
