# Generated by Django 4.0.7 on 2022-12-23 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_rename_site_notification_account_site_promotion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="notification_settings",
        ),
    ]
