# Generated by Django 4.0.7 on 2022-10-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='subscriptions',
        ),
    ]
