# Generated by Django 4.0.7 on 2022-09-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorinfo',
            name='identity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='subscription_fee',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
