# Generated by Django 4.0.7 on 2022-12-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_account_notification_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='btc_wallet_balance',
            field=models.DecimalField(decimal_places=50, default=1.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='usd_wallet_balance',
            field=models.DecimalField(decimal_places=10, default=17000.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='creatorinfo',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
