# Generated by Django 4.0.7 on 2022-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_creatorinfo_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='btc_wallet_balance',
            field=models.DecimalField(decimal_places=50, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='usd_wallet_balance',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
