# Generated by Django 4.0.7 on 2022-12-30 16:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_btc_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='btc_wallet_balance',
            field=models.DecimalField(decimal_places=50, default=1.0, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='account',
            name='usd_wallet_balance',
            field=models.DecimalField(decimal_places=10, default=17000.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
