# Generated by Django 4.0.7 on 2022-10-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorinfo',
            name='subscription_fee',
        ),
        migrations.AddField(
            model_name='creatorinfo',
            name='subscription_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=50, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='creatorinfo',
            name='subscription_fee_currency',
            field=models.CharField(blank=True, choices=[('usd', 'United States Dollar'), ('btc', 'Bitcoin')], default='usd', max_length=3),
        ),
    ]
