# Generated by Django 4.0.7 on 2022-10-14 19:12

from django.db import migrations
import media.media_paths
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_creatorinfo_subscription_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cover_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=media.media_paths.cover_photos_path),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=media.media_paths.profile_photos_path),
        ),
    ]
