# Generated by Django 4.0.7 on 2022-10-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_photo_image_alter_video_video'),
        ('accounts', '0011_alter_account_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='purchased_videos',
            field=models.ManyToManyField(related_name='buyers', through='video_purchases.Purchase', to='media.video'),
        ),
    ]
