# Generated by Django 4.0.7 on 2022-10-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('accounts', '0012_account_purchased_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='post_comments',
            field=models.ManyToManyField(related_name='commented_on_by', through='posts.Comment', to='posts.post'),
        ),
        migrations.AddField(
            model_name='account',
            name='post_likes',
            field=models.ManyToManyField(related_name='liked_by', through='posts.Like', to='posts.post'),
        ),
    ]
