# Generated by Django 4.0.7 on 2022-10-23 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_account_post_comments_account_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorinfo',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='creator_info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
