# Generated by Django 4.0.7 on 2022-10-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_creatorinfo_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_creator',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
