# Generated by Django 4.0.7 on 2022-10-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_account_is_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
