# Generated by Django 4.0.7 on 2022-10-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_public_id'),
        ('accounts', '0017_alter_creatorinfo_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='saved_videos',
            field=models.ManyToManyField(related_name='saves', to='posts.post'),
        ),
    ]
