# Generated by Django 4.0.7 on 2022-10-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_account_saved_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='saved_videos',
        ),
    ]
