# Generated by Django 4.0.7 on 2022-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_public_id'),
        ('accounts', '0019_remove_account_saved_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='saved_videos',
            field=models.ManyToManyField(related_name='saves', through='video_saves.VideoSave', to='posts.post'),
        ),
    ]
