# Generated by Django 4.0.7 on 2022-10-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_account_saved_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='purchased_videos',
        ),
    ]
