# Generated by Django 4.0.7 on 2022-10-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_purchase_cost_amount_and_more'),
        ('accounts', '0021_remove_account_purchased_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='purchased_videos',
            field=models.ManyToManyField(related_name='buyers', through='video_purchases.Purchase', to='posts.post'),
        ),
    ]
