# Generated by Django 4.0.7 on 2022-11-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_account_purchased_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_online',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
