# Generated by Django 4.0.7 on 2022-11-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_account_last_online_account_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='subscriptions',
        ),
    ]
