# Generated by Django 4.0.7 on 2022-11-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_view'),
        ('accounts', '0025_account_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='post_views',
            field=models.ManyToManyField(related_name='viewed_by', through='posts.View', to='posts.post'),
        ),
    ]
