# Generated by Django 4.0.7 on 2022-11-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_uniqueview'),
        ('accounts', '0026_account_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='unique_post_views',
            field=models.ManyToManyField(related_name='unique_viewers', through='posts.UniqueView', to='posts.post'),
        ),
    ]
