# Generated by Django 4.0.7 on 2022-11-28 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_creatorinfo_feed_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cancelled_subscriptions',
            field=models.ManyToManyField(related_name='cancelled_subscribers', through='subscriptions.CancelledSubscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
