# Generated by Django 4.0.7 on 2022-10-09 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content_type', models.CharField(choices=[('post', 'Feed post'), ('chat', 'Private message')], max_length=4)),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='photos/%Y/%m/%d')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
