# Generated by Django 4.0.7 on 2022-12-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
