# Generated by Django 4.0.7 on 2022-09-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('sub', 'Subscription payment'), ('buy', 'Single video purchase payment'), ('tip', 'Casual creator tipping'), ('req', 'Special request payment')], max_length=10),
        ),
    ]
