# Generated by Django 4.0.7 on 2022-12-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_withdrawalrequest_handled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdrawal'), ('subscribe', 'Subscription payment'), ('buy', 'Video purchase'), ('tip', 'Creator tip'), ('request', 'Special request payment')], default='withdraw', max_length=10),
        ),
    ]
