# Generated by Django 4.0.7 on 2022-09-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='platform_fee',
            field=models.DecimalField(decimal_places=50, default=0, max_digits=100),
        ),
    ]
