# Generated by Django 4.0.7 on 2022-09-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_platform_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='record_is_balanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_received',
            field=models.DecimalField(decimal_places=50, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_sent',
            field=models.DecimalField(decimal_places=50, default=0.0, max_digits=100),
        ),
    ]
