# Generated by Django 4.0.7 on 2022-12-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_cancelledsubscription_fee_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontransaction',
            name='subscription',
        ),
    ]
