# Generated by Django 4.0.7 on 2022-12-31 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('subscriptions', '0003_remove_subscriptiontransaction_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='task',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
            preserve_default=False,
        ),
    ]
