# Generated by Django 4.0.7 on 2022-11-20 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_alter_chatmessage_media_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fee_currency', models.CharField(choices=[('usd', 'United States Dollar'), ('btc', 'Bitcoin')], default='usd', max_length=3)),
                ('fee_amount', models.DecimalField(decimal_places=50, default=0.0, max_digits=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chatmessage')),
            ],
        ),
    ]
