# Generated by Django 4.0.7 on 2022-11-20 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_alter_chatmessage_media_id_and_more'),
        ('special_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagepurchase',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagepurchase',
            name='video_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.chatmessage'),
        ),
    ]
