# Generated by Django 4.0.7 on 2022-12-10 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('selfie', 'Selfie'), ('doc', 'Passport/ Id card')], max_length=10)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ImageField(upload_to='id_uploads')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
