# Generated by Django 4.0.7 on 2022-12-10 09:40

from django.db import migrations
import media.media_paths
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_alter_idupload_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idupload',
            name='upload',
            field=versatileimagefield.fields.VersatileImageField(upload_to=media.media_paths.upload_id_path),
        ),
    ]
