# Generated by Django 4.0.7 on 2022-12-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verifications", "0003_alter_idupload_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="idupload",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
