# Generated by Django 4.0.7 on 2022-10-13 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('fee_currency', models.CharField(choices=[('usd', 'United States Dollar'), ('btc', 'Bitcoin')], default='usd', max_length=3)),
                ('fee_amount', models.DecimalField(decimal_places=50, default=0.0, max_digits=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.video')),
            ],
        ),
        migrations.CreateModel(
            name='NullifiedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_nullification', models.DateTimeField(auto_now_add=True)),
                ('time_of_initial_purchase', models.DateTimeField()),
                ('fee_currency', models.CharField(choices=[('usd', 'United States Dollar'), ('btc', 'Bitcoin')], default='usd', max_length=3)),
                ('fee_amount', models.DecimalField(decimal_places=50, default=0.0, max_digits=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.video')),
            ],
        ),
        migrations.CreateModel(
            name='CancelledPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_cancellation', models.DateTimeField(auto_now_add=True)),
                ('time_of_initial_purchase', models.DateTimeField()),
                ('fee_currency', models.CharField(choices=[('usd', 'United States Dollar'), ('btc', 'Bitcoin')], default='usd', max_length=3)),
                ('fee_amount', models.DecimalField(decimal_places=50, default=0.0, max_digits=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.video')),
            ],
        ),
    ]
