# Generated by Django 4.0.7 on 2022-10-31 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_purchase_cost_amount_and_more'),
        ('video_purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelledpurchase',
            name='video',
        ),
        migrations.RemoveField(
            model_name='nullifiedpurchase',
            name='video',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='video',
        ),
        migrations.AddField(
            model_name='cancelledpurchase',
            name='video_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nullifiedpurchase',
            name='video_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='video_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
    ]
