# Generated by Django 4.0.7 on 2022-10-14 19:12

import django.core.validators
from django.db import migrations, models
import media.media_paths
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to=media.media_paths.photo_uploads_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=media.media_paths.video_uploads_path, validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
