# Generated by Django 4.0.7 on 2022-10-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_photo_image_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='puchase_cost_amount',
            field=models.DecimalField(blank=True, decimal_places=50, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='video',
            name='purchase_cost_currency',
            field=models.CharField(blank=True, choices=[('usd', 'United States Dollar'), ('btc', 'Bitcoin')], default='usd', max_length=3),
        ),
    ]
