# Generated by Django 4.0.7 on 2022-10-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_video_puchase_cost_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='puchase_cost_amount',
            new_name='purchase_cost_amount',
        ),
    ]
