# Generated by Django 4.0.7 on 2022-10-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_rename_puchase_cost_amount_video_purchase_cost_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='media',
        ),
    ]
