# Generated by Django 4.0.7 on 2022-10-30 21:25

import django.core.validators
from django.db import migrations
import media.media_paths
import videothumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_rename_image_photo_media_rename_video_video_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='media',
            field=videothumbs.fields.VideoThumbnailField(upload_to=media.media_paths.video_uploads_path, validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
