# Generated by Django 4.0.7 on 2022-10-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_video_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='purchase_cost_amount',
        ),
        migrations.RemoveField(
            model_name='video',
            name='purchase_cost_currency',
        ),
    ]
