# Generated by Django 4.0.7 on 2022-11-12 16:35

from django.db import migrations
import media.media_paths
import media.validators
import videothumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_remove_video_purchase_cost_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='media',
            field=videothumbs.fields.VideoThumbnailField(upload_to=media.media_paths.video_uploads_path, validators=[media.validators.FileMimeValidator()]),
        ),
    ]
