# Generated by Django 4.0.7 on 2022-11-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_alter_video_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='video',
            name='content_type',
        ),
    ]
