# Generated by Django 4.0.7 on 2022-12-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="viewed_on_site",
            field=models.BooleanField(default=False),
        ),
    ]
