# Generated by Django 4.0.7 on 2022-12-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notificatio_record__aaee4a_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='viewed_on_site',
        ),
    ]
